### ISSUE TITLE
Add custom analytics events for entering VR (and HMD state)

### ISSUE THREAD

**Issue by cvan** [aframevr/aframe-site#116]
We need to know how many folks have an Oculus/Vive HMD, how many have the WebVR Enabler Add-on installed (or Chrome experimental builds), and how many have entered VR mode (properly).

**Comment by cvan** [comment]
See MozVR/webvr-addon#29.

**Comment by cvan** [comment]
We'll need to first `postMessage` to https://aframe.io/aframe/examples/ to tell the pages to `postMessage` to the parent window when the "Enter VR" button is clicked.

**Comment by ngokevin** [comment]
wontfixing due to the effort of getting post message hooks into a-frame, releasing, then handling/maintaining site-side.
