### ISSUE TITLE
Get `marked` to ignore line breaks in paragraph text

### ISSUE THREAD

**Issue by cvan** [aframevr/aframe-site#117]

**Comment by cvan** [comment]
See https://github.com/aframevr/aframe-site/commit/3da38fb8fdcfe39de8c77bff5d54b553e047b0ae#commitcomment-15139098

**Comment by ngokevin** [comment]
This would be nice for vim users like me. Easier to navigate when it's broken up.

**Comment by ngokevin** [comment]
I set `breaks: true` in the config, but still not working

**Comment by ngokevin** [comment]
https://github.com/aframevr/aframe-site/pull/261
