### ISSUE TITLE
Version the docs

### ISSUE THREAD

**Issue by cvan** [aframevr/aframe-site#121]
They used to be versioned. But it was a premature optimisation. Now we need to. See  https://github.com/aframevr/aframe/issues/352

**Comment by ngokevin** [comment]
What the implementation steps to this? Shove the old docs in a folder, and start a new folder?

**Comment by cvan** [comment]
> What are the implementation steps for this? Shove the old docs in a folder, and start a new folder? Going to need to start writing soon.

I wanted to talk to you about this. Let's chat tomorrow in the office. But I wanted to shove them in a folder in `https://github.com/aframevr/aframe/tree/dev/docs/0.2.0`

**Comment by cvan** [comment]
Also see #123 for details about what I want to do next.

**Comment by cvan** [comment]
WONTFIX, but docs are sourced from `aframe` repo now (see #123).

**Comment by ngokevin** [comment]
I have a solution using `multidep`

**Comment by cvan** [comment]
oh this is awesome - didn't know this existed!
