### ISSUE TITLE
Document <a-cone> template

### ISSUE THREAD

**Issue by cvan** [aframevr/aframe-site#127]
https://github.com/aframevr/aframe/pull/337

/cc @cemkod

**Comment by cemkod** [comment]
You can assign this to me

**Comment by cemkod** [comment]
This one also seems to be blocked by document versioning of the docs: https://github.com/aframevr/aframe-site/issues/121

**Comment by cvan** [comment]
If yo'd like, you could write the doc though. We just won't merge it yet.

**Comment by ngokevin** [comment]
Handled at https://github.com/aframevr/aframe/issues/949
