### ISSUE TITLE
Document <a-ring> template

### ISSUE THREAD

**Issue by cvan** [aframevr/aframe-site#128]
https://github.com/aframevr/aframe/pull/336

/cc @cemkod

**Comment by cemkod** [comment]
You can assign this to me

**Comment by cemkod** [comment]
@cvan 
https://github.com/aframevr/aframe doesn't yet have the ring template on the master branch.
Should I still link https://github.com/aframevr/aframe/blob/master/elements/templates/a-ring.html for the source in the documentation?

**Comment by cvan** [comment]
@cemkod this is probably also blocked on versioning the docs: #121

**Comment by ngokevin** [comment]
Handled at https://github.com/aframevr/aframe/issues/949
