### ISSUE TITLE
Better document model options

### ISSUE THREAD

**Issue by cvan** [aframevr/aframe-site#132]
per https://github.com/aframevr/aframe-core/pull/747#issuecomment-170712451:

> we should probably document somewhere in the docs the support for OBJ/COLLADA/gLTF internally in aframe-core, which things already have third-party components, and which things are upcoming.
> 
> https://aframe.io/docs/primitives/a-model.html
> https://aframe.io/docs/components/loader.html

**Comment by ngokevin** [comment]
Handled by https://github.com/aframevr/aframe/issues/949
