### ISSUE TITLE
Document in FAQ link traversal (limitations, workarounds, future)

### ISSUE THREAD

**Issue by cvan** [aframevr/aframe-site#133]
We've been getting this question a lot in the A-Frame and WebVR Slacks and on Twitter. I've been directing most folks to this thread: https://github.com/aframevr/aframe/issues/341#issuecomment-169952111

We should have a section that covers in depth the following:

1. known current limitations (with piggybacking the Fullscreen API, permissions, cross-origin linking, Chromium allowing only canvas to be fullscreened, so iframe hack works in only Firefox, etc.)
2. workarounds/hacks we've created (HIRO's, VRLoader, [@vihart's linking experiments](https://github.com/vihart/webVR-playing-with), [A-Frame scene swapping approach](https://github.com/aframevr/aframe/pull/105), etc.)
3. future true link traversal in a WebVR API (in progress, expect public discussion and spec soon; perhaps keep regularly posting progress to MozVR Blog)

**Comment by ngokevin** [comment]
covers it a bit now
