### ISSUE TITLE
Link to royalty-free/public domain stock assets

### ISSUE THREAD

**Issue by cvan** [aframevr/aframe-site#141]
We're getting this question a lot on Slack, Twitter, and Reddit.

Folks are trying to find royalty-free/public domain textures, audio clips, equirectangular photos/videos, models.

Here are a few that come to mind:

* http://clara.io
* http://freesound.com
* https://www.flickr.com/search/?text=equirectangular&license=4%2C5%2C9%2C10 (which we link to from the [`<a-sky> docs`](https://aframe.io/docs/primitives/a-sky.html#Image_format))
* https://github.com/neutraltone/awesome-stock-resources

**Comment by ngokevin** [comment]
https://3dwarehouse.sketchup.com/ is awesome

**Comment by ngokevin** [comment]
added to faq/docs
