### ISSUE TITLE
Update FAQ for 0.2.0

### ISSUE THREAD

**Issue by ngokevin** [aframevr/aframe-site#152]
Most common questions:

- iOS + video
- iframes (see [this Reddit post for inspiration](https://www.reddit.com/r/WebVR/comments/47u51p/render_html_pageiframe_inside_webvr_follow_up_from/))

**Comment by cvan** [comment]
* Link traversal
* new WebVR 1.0 API

**Comment by cvan** [comment]
* same-origin issues/CORS
* where to find free assets (https://aframe.io/faq/#Where_can_I_find_assets_3F should be amended with links to clara.io, Flickr equirectangular collection [which is linked to from https://aframe.io/docs/primitives/a-sky.html], etc.)

**Comment by cvan** [comment]
- DOM and HTML in WebGL? iframes? how?
- how do I make responsive scenes with responsive controls?
- why do videos not autoplay on Chrome for Android? fix?
- why do videos not play inline on iOS? fix?
- how can I do link traversal?
- what will the new WebVR API offer? when will it be out?
- how can I get my scene on Gear VR?
