### ISSUE TITLE
Improve navigation of examples on Cardboard/mobile

### ISSUE THREAD

**Issue by cvan** [aframevr/aframe-site#163]
Using the Cardboard 2.0 button or something to advance (if we can). Voice controls are neat but unreliable and available for only Chrome for Android (and you have to be in a quiet environment).

**Comment by ngokevin** [comment]
handled @ https://github.com/aframevr/aframe/pull/1248

**Comment by cvan** [comment]
I'm a bit confused?

**Comment by ngokevin** [comment]
wontfixing, this would be hijacking controls for the scene.
