### ISSUE TITLE
TWIA: Add remaining pieces from Tumblr

### ISSUE THREAD

**Issue by cvan** [aframevr/aframe-site#220]
Not necessarily all TWIA material, but we should consider keeping at least some of these case studies:

- [x] https://aframevr.tumblr.com/post/135370463589/aframe-cinema4d-shopping-scene
- [x] https://aframevr.tumblr.com/post/135374507740/spheres-and-fog
- [x] https://aframevr.tumblr.com/post/135674561570/bmann-flickr-cc-textures
- [x] https://aframevr.tumblr.com/post/135676071805/charleston
- [x] https://aframevr.tumblr.com/post/137188100105/popmotion-physics-and-animation-with-aframe
- [x] https://aframevr.tumblr.com/post/137229500965/test-scape
- [x] https://aframevr.tumblr.com/post/137637834965/drawvr-minecraft
- [x] https://aframevr.tumblr.com/post/137799532420/solar-system-in-webvr-by-jmvisualcreativity
- [x] https://aframevr.tumblr.com/post/137799786220/360-degree-photosphere-by-ideaspacevr

**Comment by ngokevin** [comment]
OK, I missed those. Didn't see the pagination.

**Comment by cvan** [comment]
Yeah, https://aframevr.tumblr.com/archive

I have an issue in Asana to improve pagination of that theme.

**Comment by ngokevin** [comment]
OK https://github.com/aframevr/aframe-site/pull/214

**Comment by cvan** [comment]
:tada:
