### ISSUE TITLE
Update FAQ to mention that `webkit-playsinline` gets set on all videos

### ISSUE THREAD

**Issue by cvan** [aframevr/aframe-site#224]
Per https://github.com/aframevr/aframe-site/blob/master/src/faq/index.md#why-does-my-video-not-play-on-mobile

```
2. Set the `webkit-playsinline` attribute to the video element.
```

Since aframevr/aframe#1179, all videos now have this attribute and can be played inline when added to homescreen.

**Comment by amitsin6h** [comment]
want to work assign me @cvan

**Comment by ngokevin** [comment]
done
