### ISSUE TITLE
Add pagination to blog

### ISSUE THREAD

**Issue by cvan** [aframevr/aframe-site#228]
https://aframe.io/blog/

**Comment by cvan** [comment]
On my Cable connection, with a clear cache, these are the network stats from loading the [Blog index page](https://aframe.io/blog/):

* 2.2 minutes (16.31 seconds of rendering time - probably mostly from the GIFs)
* 100 MB
* 252 requests

Tried flipping this but did not work: https://github.com/aframevr/aframe-site/blob/3d49f21/_config.prod.yml#L56-L62

Currently troubleshooting…

**Comment by ngokevin** [comment]
Let me know if you have any tips/guidance. I've been wanting this, but was a bit too lazy to dive into Hexo.

**Comment by cvan** [comment]
Yeah, I spent quite a bit of time but couldn't figure it out. After I get a few things done this week, I'll take another stab. I saw reports on hexo forums and Git repos of people being confused with how to enable it as well.

**Comment by ngokevin** [comment]
Could not find documentation on how to do it either. Did it manually with a small generator script, better than some magic config/plugin.

https://github.com/aframevr/aframe-site/pull/387
