### ISSUE TITLE
awoa 11

### ISSUE THREAD

**Issue by ngokevin** [aframevr/aframe-site#233]
- [ ] audio visualizer components
- [ ] purple rain
- [ ] entity generator component
- [ ] https://t.co/riWLK3B1b8
- [ ] starfox
- [ ] https://www.ideaspacevr.org/

- [ ] https://www.youtube.com/watch?v=f2pu-oMspLs
- [ ] https://github.com/ngokevin/beaverbarcamp-presentation (with video)
- [ ] https://github.com/donmccurdy/aframe-extras/blob/master/src/primitives/a-ocean.js
- [ ] https://github.com/donmccurdy/aframe-extras/blob/master/src/primitives/a-grid.js
- [ ] https://sandbox.donmccurdy.com/vr/island/
- [ ] https://github.com/dbradleyfl/aframe-gridhelper
- [ ] showcase http://tinyhandsfortrump.net/ / http://lindseymysse.com/
- [ ] https://blog.neondaylight.com/build-a-simple-web-vr-ui-with-a-frame-a17a2d5b484#.hg6cb6hd8

**Comment by cvan** [comment]
- [ ] http://vr.greenlaserpointerstore.com/
- [ ] http://drawvr.com/lava-cave/
