### ISSUE TITLE
Does A-Frame support HTC Vive and its hand tracking input?

### ISSUE THREAD

**Issue by runvnc** [aframevr/aframe-site#237]

**Comment by ngokevin** [comment]
Yes. Alongside Chromium builds. https://aframe.io/faq/#Does-A-Frame-support-X-feature

WebVR 1.0 work is currently being done. I will be working on components/controls for HTC Vive hand controllers soon.

**Comment by cvan** [comment]
@ngokevin: can we add this to the FAQ?

**Comment by runvnc** [comment]
Thanks for clarifying guys.  To me this project is leading the way in this space and more generally in terms of software design for many types of applications.

**Comment by orta** [comment]
Might be worth adding this to the front-page? I initially dismissed this project when I first researched doing VR with web-tech as not supporting it:

<img width="367" alt="screen shot 2016-07-07 at 07 53 42" src="https://cloud.githubusercontent.com/assets/49038/16652354/03068258-4418-11e6-9d8f-882839252eb6.png">

**Comment by cvan** [comment]
Agreed, thanks for mentioning. Currently, HTC Vive support hasn't landed in our stable release but it's coming in the next few weeks. And we will be refreshing the site as well to reflect that and more. Thanks for commenting!

**Comment by orta** [comment]
Awesome 💯

**Comment by MauiJerry** [comment]
as a long time vr guy just diving into vive and web vr, I'm looking forward to this.  ECS are familiar and good choice.  Since I have a vive and doing work there, I'm excited to see A-Frame may be a good system to work with.

**Comment by ngokevin** [comment]
done a while back
