### ISSUE TITLE
AWOA 12

### ISSUE THREAD

**Issue by cvan** [aframevr/aframe-site#239]
- [ ] http://www.skyislandsvr.com/pages/mossmarch.html
- [ ] http://georational.github.io/helloWorldVR.html
- [ ] http://www.anj.fyi/world/ (maybe?)
- [ ] https://www.scenevr.com/scenes/557/view (https://medium.com/@bnolan/lightmapping-on-the-server-5485177ef2fa#.vsdt7yeto)

**Comment by ngokevin** [comment]
Will have this today.

**Comment by ngokevin** [comment]
Published a draft, but I found I need to add a few more. Will get it in a couple hours.

**Comment by ngokevin** [comment]
https://aframe.io/blog/awoa-12/
