### ISSUE TITLE
Add margin between AWOA image thumbnails at mobile width

### ISSUE THREAD

**Issue by cvan** [aframevr/aframe-site#248]
### at mobile width

![image](https://cloud.githubusercontent.com/assets/203725/15350858/b0679540-1c90-11e6-90fe-a90596822c10.png)

vs.
### at desktop width

![image](https://cloud.githubusercontent.com/assets/203725/15350862/b5a3f800-1c90-11e6-926d-4fec22ca8d20.png)

**Comment by amitsin6h** [comment]
want to work assign me @ngokevin

**Comment by ngokevin** [comment]
wontfix, moved to new layout
