### ISSUE TITLE
Document <a-circle>

### ISSUE THREAD

**Issue by chriscar** [aframevr/aframe-site#250]

**Comment by cvan** [comment]
Docs haven't been written yet, sorry.

(@ngokevin: Perhaps this issue should live in the A-Frame repo?)

**Comment by ngokevin** [comment]
I don't mind whether this repo or A-Frame repo. I try to do a clean sweep of all the docs before each release. As long as it's filed, I can find it.

**Comment by ngokevin** [comment]
Handled at https://github.com/aframevr/aframe/pull/1494
