### ISSUE TITLE
more subtle inline code block typography

### ISSUE THREAD

**Issue by ngokevin** [aframevr/aframe-site#259]
Currently, it's given its own background/padding + highlight color + different font-size. Documentation gets a bit distracting since paragraphs are littered with `these code blocks`. And when documenting API with code-block-headings, it's hard to tell the structure of the page since some headings become orange and some are normal.

<img width="683" alt="screen shot 2016-05-31 at 12 15 49 pm" src="https://cloud.githubusercontent.com/assets/674727/15687417/6e8768c8-2729-11e6-83cd-87544896e840.png">

Make it more subtle by perhaps just giving it a monospace font + very slightly increased font-size/weight, like Django docs:

<img width="410" alt="screen shot 2016-05-31 at 12 14 55 pm" src="https://cloud.githubusercontent.com/assets/674727/15687397/4f943928-2729-11e6-8ef0-f1287fce5156.png">

**Comment by cvan** [comment]
I can dig it

**Comment by ngokevin** [comment]
Fixed ^
