### ISSUE TITLE
Getting Started > Builds buttons look wonky

### ISSUE THREAD

**Issue by cvan** [aframevr/aframe-site#265]
1. Load [https://aframe.io/docs/guide/getting-started.html#Builds](https://aframe.io/docs/guide/getting-started.html#Builds) or [http://localhost:4000/docs/guide/getting-started.html#builds](http://localhost:4000/docs/guide/getting-started.html#builds)
2. Notice breakage

![image](https://cloud.githubusercontent.com/assets/203725/15693055/2e071be0-2747-11e6-90ea-18b03c3f330b.png)

Looks like a line break is missing between the two buttons.

**Comment by ngokevin** [comment]
maybe the github line breaks change

**Comment by ngokevin** [comment]
This solves on master https://github.com/aframevr/aframe/commit/c5ba66b85a69bc3fdac39ed1811d340312e5daf6

For 0.2.0, might employ some CSS

**Comment by cvan** [comment]
still broken on master:

![image](https://cloud.githubusercontent.com/assets/203725/16503472/0436b31e-3ec8-11e6-922b-048827ab875a.png)

that's because the `aframe` version we're pointing to is out of date. can we bump?

https://github.com/aframevr/aframe/commit/c5ba66b from May 31
https://github.com/aframevr/aframe/commit/7dfc811 from Apr 28
