### ISSUE TITLE
markdown partials

### ISSUE THREAD

**Issue by ngokevin** [aframevr/aframe-site#266]
I have some table rows (material properties) that I want to repeat across many docs (primitives pages). I am currently linking to a reference page, but readers will just skip over it.

Maybe something like...somehow:

```
| Header | Desc |
| ---------- | ------- |
| blah | blah |
{# include ../../material_table_rows.md #}
```

**Comment by cvan** [comment]
I've been meaning to try https://github.com/celsomiranda/hexo-renderer-markdown-it - perhaps it's extensible to allow Markdown includes

**Comment by ngokevin** [comment]
wontfix
