### ISSUE TITLE
Prominently link to GitHub (with verison) + Download ("Getting Started")

### ISSUE THREAD

**Issue by cvan** [aframevr/aframe-site#268]
It looks like "Install" nav link has been removed from the sidebar. TBH, "Docs" is better anyway.

But, IMO, we should have a very prominent "Install" or "Download" link on both the homepage/examples and docs/secondary pages - either as a header or sidebar.

![image](https://cloud.githubusercontent.com/assets/203725/15759311/100bade0-28c3-11e6-9927-6bc11fa3540a.png)
![image](https://cloud.githubusercontent.com/assets/203725/15759337/24deeef8-28c3-11e6-8726-19b56e102766.png)
![image](https://cloud.githubusercontent.com/assets/203725/15759355/348d48fe-28c3-11e6-860a-f40758e4f50d.png)
![image](https://cloud.githubusercontent.com/assets/203725/15759474/962cf154-28c3-11e6-9e00-a2a7996fbd62.png)

related: #21, #191

**Comment by ngokevin** [comment]
Should we use a GitHub ribbon?

**Comment by cvan** [comment]
> Should we use a GitHub ribbon?

they look tacky IMO. I like Terraform's, or in fact any other others' treatment above

**Comment by ngokevin** [comment]
Yeah agreed, not the sleekest UI and unsexy.

Would note that some advantages are that developers are accustomed to the ribbon, knowing where it leads, it's a big click target, and it gives off an open source feeling.

**Comment by cvan** [comment]
I've seen it less and less. "Fork me" isn't necessary what you want. Maybe people want to star it or view the source. Or know which version of A-Frame is on `master`.

Perhaps some of these:

http://tholman.com/github-corners/

http://shields.io/#downloads
http://shields.io/#social
![image](https://cloud.githubusercontent.com/assets/203725/15763680/5e729f7c-28da-11e6-8abd-e8a71a2cfd88.png)

[![npm version](https://badge.fury.io/js/aframe.svg)](https://badge.fury.io/js/aframe)

**Comment by ngokevin** [comment]
Yeah, I probably would have changed to "Star Me", but I actually do like the GitHub corners.

The social buttons, I feel like users (or at least me) are conditioned to ignore those.

**Comment by ngokevin** [comment]
wontfix, prominent CTA on aframe.io
