### ISSUE TITLE
update and agree on a single unified A-Frame motto

### ISSUE THREAD

**Issue by ngokevin** [aframevr/aframe-site#275]
Goal: Explain exactly what A-Frame is. I think we may have outgrown "Building Blocks for the VR Web" as it is no longer descriptive.

Grab bag:

- HTML
- WebVR
- Framework
- ECS
- Open-source
- <s>Responsiveness</s> (not responsiveness, but mention device support like rift/vive/cb)
- three.js framework
- ECS on DOM
- Extensible

**Comment by armthethinker** [comment]
So, is it that "Building Blocks for the VR Web" doesn't include technical components?

**Comment by ngokevin** [comment]
What do you think about `Building Blocks for the VR Web`? Actually, haven't heard any opinions about it. That could work for a tagline, that doesn't need to be technical. Might be nice to mention `WebVR`.

But I guess what I'm looking now for is a succinct answer to `"What is A-Frame?"`. If we or someone were to write an article, we'd start with `A-Frame is...`. What would come after?

**Comment by cvan** [comment]
I've been thinking about this a bit. How's this slogan + subtitle?

# A-Frame is an HTML/JS framework for creating VR-first responsive web pages.
###### Designed for creatives, developers, educators, explorers, and you.

Hopefully not too many buzzwords. But I think today the audience we are trying to / have been able to capture is people who aren't afraid of HTML and maybe a tiny bit of JS. The slogan can evolve as we build out the tools, ecosystem, and site to cater to wider audiences.

What do you think?

**Comment by cvan** [comment]
I'm drawing inspiration from the title bar of https://themanual.org/read and the mastheads of http://www.dropmark.com/ / http://www.siteleaf.com/:

![image](https://cloud.githubusercontent.com/assets/203725/17538748/2582a636-5e5d-11e6-8665-6b8f54d583b4.png)

![image](https://cloud.githubusercontent.com/assets/203725/17538767/3d56e9ac-5e5d-11e6-8123-27a5d63e3277.png)

![image](https://cloud.githubusercontent.com/assets/203725/17538757/33bc6bc4-5e5d-11e6-99ca-57b97e1a0644.png)

**Comment by cvan** [comment]
To quote [this neat guide](https://medium.com/@evejweinberg/all-the-webgl-tools-and-frameworks-i-have-looked-at-a1c22154591b#.y95zdvtw2):

> A-frame — A-Frame wraps three.js and WebGL in HTML custom elements. It lets you create VR experiences that work across desktop, iOS, Android, and the Oculus Rift.
> Is publishing to VR easy? Yes
> Do you have to code? Yes, but barely… HTML and Javascript
> Who made it? Mozilla VR team (MozVR)

I was thinking we could just show the icons (w/ tiny text labels) to list the platform compatibility in the top-right corner or somewhere.

**Comment by cvan** [comment]
https://twitter.com/ticidesign/status/763167468520996865

> Build VR experiences with just HTML! AMAZING!

I keep dwelling on how the slogan needs to clearly explain that. But it should be/can be a tad more descriptive.

**Comment by ngokevin** [comment]
> A-Frame is an HTML/JS framework for creating VR-first responsive web pages.

- I usually think about it as a WebVR framework above anything else. That way, we don't have to mention `VR-first`. It's VR-focused in general.
- Wouldn't mention responsiveness. You *could* build responsive pages (i.e., works across different "mediums"), but I'd rather recommend targeting a single platform (i.e., room-scale only, Cardboard only) at a time. Allows for better optimized experiences because if you try to incorporate Cardboard, you're forced to constrain your experience.
- Web pages or experiences? Experiences is a bit buzz-wordy, but it's a bit stronger.

This doesn't have to be on the website, I'm just thinking if we were to release an A-Frame press kit or onboarding materials, or blog post, what would *the* one sentence describing A-Frame?

**A-Frame is a WebVR framework for building virtual reality experiences with HTML.**

The three.js/ECS bits can be excluded depending on the audience (and you're still building with HTML at the end anyways), but the above should be captured regardless of audience.

> Designed for creatives, developers, educators, explorers, and you.

It sounds nice, although not super genuine. It was designed for developers primarily, and we don't have tools or workflows for creatives/educators/explorers yet. **Built by developers, loved by everyone** is more accurate.

Our stubbed byline "Make WebVR" is not too terrible. It inspires a sense of general "making" (think Maker Faire) and a call to action. "Building Blocks for the VR Web" is actually not too terrible either because it makes it sound very easy.

**Comment by dmarcos** [comment]
The word WebVR is jargon and many users don't know what WebVR entails and they don't need to know. What about:

**A-Frame, the framework for building virtual reality experiences in the Web.**

I think it's honest. It does not make promises that we won't be able to fulfill like `one line of code` or `responsive`.

**Comment by ngokevin** [comment]
I think it should mention HTML to differentiate from a JS framework like playcanvas or three. Something like (brainstorming):

`A-Frame is a web framework for building virtual reality experiences with HTML`

`A-Frame is a framework for building virtual reality experiences with HTML on the Web`

**Comment by ngokevin** [comment]
The way I see it, even *if* you use ECS, the end result and outermost abstraction layer is HTML. I do all code within components, but at the end of the day, I am attaching them through HTML.

**Comment by ngokevin** [comment]
In places where we have more room to explain (blog/article/second slide/docs), we'll definitely mention ECS. I'm just thinking purely, what would the *very first sentence* look like.

**Comment by fernandojsg** [comment]
@ngokevin yep you're right, probably something shorter and more concise and just expand it later. In that case I think I prefer `A-Frame is a web framework for building virtual reality experiences with HTML`. Adding `on the web` is little redundant yep. 
I'm not sure about @dmarcos idea about using `the` instead of `a`, I like it but at the same time I feel it sounds a little arrogant?

**Comment by ngokevin** [comment]
yeah `the` sounds a bit like marketing, like "Oreo's: America's Favorite Cookie". i don't think he was focusing on the `the` part though

**Comment by fernandojsg** [comment]
Reading it again `building VR experiences with HTML on the web` sounds for me like you're going to build them directly on the web, like with some online solution for building it.

**Comment by ngokevin** [comment]
sticking it as `web framework` sounds good to me then.

**Comment by cvan** [comment]
> I think it's honest. It does not make promises that we won't be able to fulfill like `one line of code` or `responsive`.

I like that 👍

**Comment by armthethinker** [comment]
To chime in,
- I like `A-Frame is a web framework for building virtual reality experiences` or `A-Frame is a framework for building virtual reality experiences on the web`
 - `Web framework` means web languages without having to specify in the tag line. We can say HTML and JS after the reader is hooked.
 - It's a good "grandma definition"
- I think its good to move away from `responsive`, `VR-first`, and `web page`, though I appreciate how `webVR` describes itself.
- For the subtitle, it would be a good place to mention who it is built for and the tech in some way. Brainstorming vomit:
 - `Building blocks for the VR web, powered by HTML/JS, usable on desktop and mobile-based VR`
   - My favorite
    - Not the most succinct, but mentions extensibility and modularity with `building blocks`, explicitly states languages and that one should know them to work with A-Frame, and responsiveness/robustness.
 - `Designed to be easy-to-use, yet powerful`
 - `Not your parents' webVR framework`
 - `Easy to get started with HTML, go further with JS`

**Comment by cvan** [comment]
Thanks for the feedback - good.

I'm thinking 

> A-Frame lets you code VR scenes with HTML.

or

> A-Frame is an open-source library for creating VR scenes with HTML.

**Comment by ngokevin** [comment]
Just noting it's more of a framework, not a library.

Framework: you write and hook in code, we call the code. Provides an opinionated (although optional) structure for building VR apps
Library: we provide code, you call the code. We do provide several components and primitives, but we encourage going beyond those.

"A-Frame + Framework", they sound strong together.

**Comment by ngokevin** [comment]
Just noting it's more of a framework rather than a library.  "A-Frame + Framework" sounds strong:

Framework: you write and hook in code, we call the code. Provides an opinionated (although optional) structure for building VR apps
Library: we provide code, you call the code. We do provide several components and primitives, but we encourage going beyond those.

- "Lets you" is a bit weak, it sounds like a sentence in an introductory paragraph rather than the primary tagline. The primary tagline should always start with **X is ___**
- Would avoid saying "code" for the motto
-"Building" sounds more constructive rather than just "Creating"
- "virtual reality" over "VR" in case some people don't know
- "experiences" over "scenes" as scenes sound static. The entire movie vs. just the set.

For me, it's between:

- A-Frame is a web framework for building virtual reality experiences
- A-Frame is a framework for building virtual reality experiences on the Web
- A-Frame is a web framework for building virtual reality experiences with HTML

**Comment by ngokevin** [comment]
Or `A-Frame is a declarative framework for building virtual reality experiences on the Web`

I sort of like saying `on the Web` vs. `with HTML` because the former is about the mission and the latter is about the implementation. Adding `declarative` before `framework` makes it flow a bit smoother and more descriptive than just `a framework`

**Comment by fernandojsg** [comment]
I also prefer `on the Web` vs `with HTML`. The ones I like the most:
* A-Frame is a framework for building virtual reality experiences on the Web
* A-Frame is a declarative framework for building virtual reality experiences on the Web

**Comment by cvan** [comment]
I'm not sure the value of `declarative`. IME, not many folks, even seasonsed web devs, actually know what `declarative` means.

Why not just keep it simple with `A-Frame lets you create VR scenes with HTML`?

Or, `A-Frame is an open-source HTML markup to create VR scenes for the Web`?

Personally, I don't think `the Web` is descriptive enough; it could mean a number of things. But, really all you need is a `<script>` tag and some (custom elements) `HTML` to get an A-Frame WebVR scene up and running.

Let's figure out who our audience is. `HTML` is a dog whistle. If you're a developer or designer, you've probably at least heard of `HTML` as being an ingredient in making a web page. Not that it probably means much, but I just asked three completely non-technical folks, and they all told me that `HTML` is used to create web sites. I understand that anecdotal evidence is hard to justify marketing/copy/slogans - especially when we're dealing with both technical and non-technical audiences of varying experience.

> `A-Frame is a framework for building virtual reality experiences on the Web`
> `A-Frame is a declarative framework for building virtual reality experiences on the Web`

Would it be better to just say something like `A-Frame is a free, open-source library for creating VR web pages`? At least to me, that's more descriptive, honest, and I know what I'm getting myself into.

Let me know what y'all think.

**Comment by ngokevin** [comment]
"Declarative" is a toss up. "Declarative framework" sounds more powerful than "X with HTML" since HTML by itself is not interactive (which isn't how we want to present a VR framework). I also like presenting "declarative" since it focuses on the ends rather than the means: we use HTML because it's declarative, we don't use HTML for the sake of HTML.

I mentioned these previously:

- "X is" > "X lets us"
- "build" > "create"
- "experiences" > "scenes" > "web pages"
- "framework" > "library"
- "virtual reality" > "VR"

To add on top:

- "free / "open source" - I think for web frameworks and technologies, it's a given. If not obvious to someone, it can be quickly found out.

A-Frame is mostly developers + designers that are okay doing a bit of code (like @armthethinker) I do see the advantages of HTML clicking. But if we're going for descriptive, HTML is only a single slice / abstraction layer of A-Frame and an implementation detail. Should we describe the ends vs. the means? And if we're going for honest, at this point of time, people will need some JavaScript to implement quality experiences and ideas. 

I probably still stand by *A-Frame is a declarative framework for building virtual reality experiences on the Web*. Most honest, declarative, strongest, focusing on the grand scheme rather than the details, skewing towards developers/devsigners who are equipped to propel the ecosystem.

**Comment by cvan** [comment]
I like [Electron](http://electron.atom.io/)'s slogan:

**Electron**
> Build cross-platform desktop apps
> with JavaScript, HTML, and CSS

![image](https://cloud.githubusercontent.com/assets/203725/18154395/307ee902-703f-11e6-9fba-a186b97191dc.png)

**A-Frame**
> Build Virtual Reality web sites
> with HTML and JavaScript

 <br>

> If you can build a website, you can build a WebVR scene. A-Frame is a framework for creating native applications with web technologies such as JavaScript and HTML It takes care of the hard parts so you can focus on building your VR experience.

<br><hr><br>

What about shortening this

> A-Frame is a declarative framework for building virtual reality experiences on the Web.

to one of these

> A-Frame is a web framework for building virtual reality experiences.
> A-Frame is a web framework for building experiences for virtual reality.

?

> HTML is a nice dog whistle, but it does trade off honesty for attention. It does also limit it the scope to code when we could be more inclusive of cross-disciplines.

I have to say that for me, as a developer, "declarative framework for […] the Web" or "web framework" implies I need to learn some new JS framework, its patterns, and write a ton of JS. Do you think possibly other folks might get the same impression? With A-Frame, you can build a compelling VR scene with mostly (custom-element markup) HTML and a little JS sprinkled in.

Inspired by my tagline suggestion above that was inspired by Electron's tagline, if we want to be most honest, what do you think of this one below?

> A-Frame is a web framework for building virtual reality experiences using HTML and JavaScript.

That to me feels the most honest and feels like it wouldn't scare away technical nor non-technical folks.

I think of "Backbone/Angular/React/Django/Express/etc." when I hear the word "framework." When I hear "declarative" – and, mind you, I'm a dev who knows what this word means – I think programming buzzword and "is this like Polymer? Polymer's bloated. Hmm, I'm not sure this is for me either."

> I probably still stand by _A-Frame is a declarative framework for building virtual reality experiences on the Web_. Most honest, declarative, strongest, focusing on the grand scheme rather than the details, skewing towards developers/devsigners who are equipped to propel the ecosystem.

I think we're close. At the cost of sounding cheesy and lacking a good metaphor… Like good jazz, let's keep building on one another's comments and ideas until the tagline sounds and feels right to everyone. It's important to choose our words carefully so as to not alienate anyone (or too many people, if we're okay with alienating some folks).

If I had to rank the defining properties of a good software tagline, I'd say for me, they'd be these:

1. **Honesty.** This software does not feel gimmicky or buzzwordy. The tagline is accurate.
2. **Clarity/Conciseness.** This software's tagline is short and accurate easy enough for my eyes to scan quickly and proceed with interest - that is, not too long for my eyes to glaze over it.
3. **Interestingness.** This software doesn't scare me. And, it doesn't sound like a toy. In fact, my interest is growing.

Another thing I wanted to get folks' input on is the term "experience." Based on everyone's usage of "experience" to describe what you can build with A-Frame, I assume that's a non-negotiable? When people ask me what my team does with VR, I tend to try to use the term "experience" (because I don't want them to think "VR is just for gamers"), but IME when I mention "game," "web page," "world," "scene," and even "content," folks seem to immediately grasp what I'm talking about. Again, these are merely personal anecdotes, so possibly take this with a grain of salt.

In any event, taglines for a non-techie (i.e., taglines that don't contain any technical jargon/acronyms) might go something like these:

> A-Frame is a framework for building virtual-reality worlds that people can experience with a browser.

or

> A-Frame is a framework for building web pages that are 3D worlds you can experience in VR – and even walk inside.

That's at least how I explain A-Frame/WebVR to people, and they seem to get it instantly. I understand that these two taglines use "dumbed-down" terminology to get the point across, but they are definitely honest and clear. Not saying that I'd recommend using these taglines, but just a point worth addressing I thought.

Another thought: @ngokevin, I saw you mention device support in your grab bag of ideas in the first comment.

If we wanted to cater to both web developers, designers, Unity/Unreal devs, educators/students/explorers, etc., perhaps something like this tagline below would resonate with them?

> A-Frame is a web framework for building experiences for the HTC Vive and Oculus Rift.

Thoughts?

**Comment by cvan** [comment]
Thinking about this a bit, and talking to some folks.

Today, someone opens a VR application from Oculus Home or Steam to "experience" VR. As a noun, it seems possibly redundant and unclear to mention it in describing A-Frame. You could say something like

> A-Frame is a framework for creating VR web apps.

I'm dwelling on "framework"; it seems to be a term pretty specific to computers (and Google searches and Wikipedia seem to confirm this suspicion). In recent memory, I can't recall hearing anyone outside of tech using the term.

Perhaps this:

> A-Frame is a platform for creating VR games and apps for the browser.

And, if we want to mention devices, possibly we could go with:

> A-Frame is a platform for creating VR web apps for the HTC Vive, Oculus Rift, and Samsung Gear VR.

Still thinking…

**Comment by ngokevin** [comment]
Okay, here's what I think:

> I have to say that for me, as a developer, "declarative framework for […] the Web" or "web framework" implies I need to learn some new JS framework, its patterns, and write a ton of JS. Do you think possibly other folks might get the same impression? With A-Frame, you can build a compelling VR scene with mostly (custom-element markup) HTML and a little JS sprinkled in.

I think that's the most honest and up front even if it sounds potentially scarier. If we want to build a compelling VR experience at this stage, there is some learning involved about the framework. I don't think plopping a model down without anything else is compelling, and we should encourage to push the boundaries of rich experiences. Perhaps people don't need any *code* if they use community components, but they still need a basic grasp of the framework in how to apply those components and how things fit together.

> Framework / Declarative

I understand how you feel about it. Though perhaps you might not be in the majority if you run away when you hear "declarative" or "framework". It is definitely the most honest and accurate description of what it is, and thus trying to avoid it is effectively sugarcoating. Like it or not, it's a framework world.

> Inspired by my tagline suggestion above that was inspired by Electron's tagline, if we want to be most honest, what do you think of this one below?

It's a nice tagline. It wouldn't be the worst for A-Frame, but each project has different priorities in what to communicate. Electron is all about actually being about to use the *languages* and makes sense to mention them. For us, we care more about the end result: compelling VR experiences on the Web. Again, ends vs. means.

> Another thing I wanted to get folks' input on is the term "experience."...folks seem to immediately grasp what I'm talking about

If honesty is the top goal, "experience" is it. The other words do not describe it completely. Even if people get what "game" or "content" or "scene" means, it doesn't matter if it's not accurate.

> In any event, taglines for a non-techie...

Developers and devsigners. The primary description of a technical tool shouldn't cater to non-techies. It is totally okay to explain it differently to your friends, have secondary descriptions, have subtitles, but the primary description should be succinct. Remember we have lots of room if we want to allow non-techies to get it: place a subtitle on the homepage, add follow-up sentences in guides, add additional slides in presentations, answer questions in person, FAQ, press kits.

> I saw you mention device support in your grab bag of ideas in the first comment...resonate with them

Probably wouldn't mention devices. It's constantly in flux. And we support more than Vive/Rift. Each device support has different capabilities and quirks so "supports" is relative. It's a great point to make immediately following the primary description though.

I hope I'm not being stubborn when I still prefer what I set on, and I read your points. I just don't think there's any room for misinterpretation, is well geared to the level of skill required for building compelling VR experiences, and encapsulates A-Frame well. Not trying to play any card of authority, but that's just from my experiences of curating every scene, talking with everyone in the community, building lots of scenes.

I do agree with your three intentions in that order: honesty / clarity / appeal. But I think your suggestions favor appeal over honesty/descriptiveness, and are missing the type of people that use A-Frame ("scaring", "resonating", "alienating", "non-techie", "outside of tech"). Happy to consider any alternatives if you re-gear your suggestions to those priorities.

**Comment by darkwing** [comment]
`A-Frame is a platform for creating VR web apps for the HTC Vive, Oculus Rift, and Samsung Gear VR.` is a good message for getting SEO juice (i.e. mentioning each device will help with search hits) but then you end up needing to expand the list when new devices come out.  You'll always lose that way.

`A-Frame is a platform for creating VR games and apps for the browser and VR devices.` is a bit broader, which I like.

One thing that would be good to work in would be "with HTML"; that's the biggest selling point, right?  The ease with which A-Frame allows you to create VR environments.  Maybe that can be left for a "sub-headline" or something though.

**Comment by cvan** [comment]
@ngokevin thanks for the thorough response. I do agree with just about everything you've said. And you've made clear some points I wasn't sure we were in agreement about (A-Frame's desired target audience today being only developers/devsigners; ). You're definitely in the trenches and building in A-Frame every day; you undeniably understand the audience we have today.

> I understand how you feel about it. Though perhaps you might not be in the majority if you run away when you hear "declarative" or "framework".

This is quite possibly true. I think "overcomplicated" when I hear "framework." To be honest, at least IME, I've never seen "declarative" used as a clarifying word in describing something in tech/software. It's void of meaning. Searching for the term ["declarative framework" on Google](https://www.google.co.jp/search?q="declarative+framework") yields literally nothing but jargon.

> It is definitely the most honest and accurate description of what it is, and thus trying to avoid it is effectively sugarcoating. Like it or not, it's a framework world.

What "it" that is a framework world? The front-end Web world? And, if that's what you mean, is that the world the one we want to enable for VR development on the Web?

> Probably wouldn't mention devices. It's constantly in flux. And we support more than Vive/Rift. Each device support has different capabilities and quirks so "supports" is relative. It's a great point to make immediately following the primary description though.

Yep, Gear VR too - and likely soon Daydream (for free, perhaps?). And, Cardboard support we already support, but I understand don't want to over-promise on.

Device support perhaps doesn't have to be mentioned in the one-liner tagline. But, it should probably be certainly be mentioned immediately alongside a description of A-Frame on the site (as it is today).

> I hope I'm not being stubborn when I still prefer what I set on, and I read your points. I just don't think there's any room for misinterpretation, is well geared to the level of skill required for building compelling VR experiences, and encapsulates A-Frame well. Not trying to play any card of authority, but that's just from my experiences of curating every scene, talking with everyone in the community, building lots of scenes.

Totally better understand your reasoning. Much appreciated, really.

@darkwing [tweeted](https://twitter.com/davidwalshblog/status/768918401007837184) the other week about A-Frame disarming Imposter Syndrome. I concede that a lot of my concern/paranoia comes from trying to empathise (over-empathise, quite possibly) with the users we might have, might want, might lose.

Over the past several months, from my perspective, I've seen in the current A-Frame community, the ones who really put their all in it (creating components, expanding their knowledge, going outside their comfort zone) – and I'm including @ngokevin, @dmarcos, @donmccurdy, @bryik, @andreasplesch, etc. in that crowd – seem to certainly be a (passionate, powerful, and necessary) minority.

I don't know how many of you there are out there. I'd certainly want everyone like y'all, who won't hesitate picking up a 3D graphics book or perusing Wikipedia articles, to feel like A-Frame is not a scary beast.

In my wall of text above (sorry for the length!), I mentioned perhaps we could shorten

> A-Frame is a declarative framework for building virtual reality experiences on the Web.

to one of these

> A-Frame is a web framework for building virtual reality experiences.

or

> A-Frame is a web framework for building experiences for virtual reality.

How do you feel about that, at least?

**Comment by andreasplesch** [comment]
Thanks for including me as a non-professional in this rather exclusive list. I am amazed at the depth of discussion going into a motto/tag line. As such, a motto is limited to a few words. To me, these should include:

1) VR
2) JS/HTML
3) web
4) 3D (many people still care about 3D graphics vs. 2D graphics, or are not familiar with the term VR)
5) experience

in order of importance. That does not leave too much space for words in between.

It is unfortunate that using 'declarative' would drive away interest although it should signal comfortable use.

I personally did not understand why 'experience' is used within VR contexts or what it may mean until I tried some of them. So it is a bit of a chicken and egg problem. Since 'reality' is already something to experience, adding 'experience' is a bit redundant (although now standard). Just saying 'building virtual realities' using the plural may suffice, if it is not too 'avantgarde', eg. would invite too many questions.

Another approach would be to go for something lighter but hinting.  After all, a motto is about marketing:

"from the Web into Goggles"
"VR for the Web"
"VR for the browser"
"Browse into Virtual Reality"

Let me also admit that as an on and off user I sometimes have a hard time recalling that 'A-frame' is the name for this platform/framework/technology/library. For me, the name does not connect to the functionality.

**Comment by dmarcos** [comment]
I stick to:

"A-Frame is a framework for building virtual reality experiences on the Web"

No jargon, no hype, honest, simple, accurate, not salesy... 

If you don't like the word `framework` I have:

- `Tool` or `Toolset`: This might be vague. What kind of tool?
- `API`:  Maybe inaccurate because a-frame comes with a visual inspector now too.

**Comment by cvan** [comment]
> Thanks for including me as a non-professional in this rather exclusive list.

@andreasplesch, I was referring to you (and the group) as advanced professionals in that list. My apologies for the poor phrasing.

**Comment by ngokevin** [comment]
I'm okay with removing "declarative" since everyone agrees on that. React also doesn't put it in their tagline, but puts it in their "big three" points: https://facebook.github.io/react/docs/why-react.html

> And, if that's what you mean, is that the world the one we want to enable for VR development on the Web?

Yeah, the front-end Web world, which revolves around frameworks. That is the world I want to enable because they are most equipped to develop rich and interactive experiences. Because...

> Over the past several months, from my perspective, I've seen in the current A-Frame community, the ones who really put their all in it (creating components, expanding their knowledge, going outside their comfort zone)...I don't know how many of you there are out there. I'd certainly want everyone like y'all, who won't hesitate picking up a 3D graphics book or perusing Wikipedia articles, to feel like A-Frame is not a scary beast.

We can enable those small minority to lead the ecosystem in components, shaders, and ideas. When they create components, more novice users are able to use them through HTML. By enabling web developers, we effectively make it easier for everyone else...like trickle-down economics that work.

Anyways, I like *A-Frame is a framework for building virtual reality experiences on the Web* or *A-Frame is a web framework for building virtual reality experiences*. This decision should be a bit simpler: do we want to emphasize that it's a way to create VR or a way to create WebVR?

**Comment by andreasplesch** [comment]
@cvan: No, I do really feel like a non-professional since I cannot spend too much time on this. No apologies needed at all.

**Comment by cvan** [comment]
> Anyways, I like *A-Frame is a framework for building virtual reality experiences on the Web* or *A-Frame is a web framework for building virtual reality experiences*. This decision should be a bit simpler: do we want to emphasize that it's a way to create VR or a way to create WebVR?

IMO, just "VR"

**Comment by ngokevin** [comment]
Sorry, wasn't asking to put "VR" vs. "WebVR". The former option emphasizes building virtual reality on **the Web**. The latter option is more about just building virtual reality, but using web technologies.

**Comment by cvan** [comment]
and I still think "on the Web" is vague. does it mean a full-blown WSIWYG like Goo Create or Vizor? does "on the Web" mean it's exported to HTML5? does "on the Web" mean I must create scenes using JS or some new templating system (e.g., JSX)?

**Comment by ngokevin** [comment]
"VR experiences on the Web" should be clear that it's for running on the Web. I don't see any indications that it connotes WSIWYG vs. export vs. JS. "Framework" is what connotes the how.

**Comment by cvan** [comment]
the Web is too vague IMO. one of @andreasplesch's suggestion was including the word `browser`.

> "VR experiences on the Web" should be clear that it's for running on the Web. I don't see any indications that it connotes WSIWYG vs. export vs. JS. "Framework" is what connotes the how.

> A-Frame is a framework for building virtual reality experiences on the Web

unclear

> A-Frame is a web framework for building virtual reality experiences

clearer

since we're talking about frameworks, I think Electron's slogan is very direct, honest, and not salesy:

> **Build cross-platform desktop apps**
> with JavaScript, HTML, and CSS

I'd recommend the latter and condensing "virtual reality" to just "VR." or do you think it's too premature for folks to know what VR stands for?

> **A-Frame is a web framework for building VR experiences**

And perhaps with a sub-tagline that isn't so wordy as this one but still gets these points across:

> Create worlds for virtual reality using HTML & JavaScript

**Comment by ngokevin** [comment]
Sounds good. I think it's okay at this point to abbreviate VR. The only people that I know that don't understand what "VR" is are the most untechnical people, a group which is fine to ignore here.

> A-Frame is a web framework for building VR experiences.

Now for a sub-tagline, which we need to brainstorm from scratch. I think at this point, we should mention languages. "Create worlds for virtual reality" might be redundant given that it's conveyed in the description. Random components:

- Building blocks
- VR / WebVR
- HTML
- JavaScript
- Make / Create
- Walk

And how long should it be? "Building blocks for the VR Web" and "with JavaScript, HTML, and CSS" are very succinct. "Walk in VR with HTML & JavaScript", "VR building blocks with HTML & JavaScript", etc?

**Comment by cvan** [comment]
I like `Walk in VR with HTML & JavaScript.` An animation of someone walking in a WebVR Holodeck really resonates with me and seems to excite folks.

**Comment by armthethinker** [comment]
I'd caution using _walking_, because Cardboard doesn't provide position tracking.

**Comment by ngokevin** [comment]
We imagine the future of VR having positional tracking and we should aim for that. But it doesn't have to be *walk* if we can think of something better.
