### ISSUE TITLE
Update Showcase

### ISSUE THREAD

**Issue by ngokevin** [aframevr/aframe-site#283]
Decide what to include in the showcase.

**Showcase Scenes:**

Both first-party and third-party scenes. Select 10-15.

- Painter
- Shooter
- Fear of the Sky
- Journey to Mars
- Anime UI
- 360 Image Browser
- Audio Visualizer
- Tiny Hands for Trump
- Panorama
- Spheres & Fog
- Wikipedia

**Showcase Components:**

Need to showcase components somewhere. Select 10-15, then link to awesome-aframe component repository. Where should we show them?

**Comment by cvan** [comment]
lol why Tiny Hands for Trump?

**Comment by ngokevin** [comment]
You can suggest more/other experiences. I think that one is fairly polished, and it's pretty current.

**Comment by ngokevin** [comment]
mostly updated a bit. can add more as we see fit
