### ISSUE TITLE
Broken link in /docs/0.2.0/guide/

### ISSUE THREAD

**Issue by torchhound** [aframevr/aframe-site#292]
The actual doc lives in aframevr/aframe but this issue seemed better suited for the site repo. In this line: "Under the hood, A-Frame is built on top of Custom Elements and is powered by three.js." the link to three.js on the live website leads to three.js.org(which is wrong/broken). In the doc at aframevr/aframe/blob/master/docs/guide/index.md it correctly leads to threejs.org.

**Comment by ngokevin** [comment]
Yeah. The only way to fix this is to cherry-pick fixes onto the old docs and release a new version, but for now, it's a lot of effort. At least 0.3.0 is coming soon.

**Comment by ngokevin** [comment]
Will leave 0.2.0 for now, but from 0.3.0 on, we are cherry-picking fixes. Thanks!
