### ISSUE TITLE
Add Contributing Guidelines

### ISSUE THREAD

**Issue by cvan** [aframevr/aframe-site#320]
We should add Contributing Guidelines (a `CONTRIBUTING.md`) à la [A-Frame's](https://github.com/aframevr/aframe/blob/master/CONTRIBUTING.md).

And, it should also be mentioned and linked to from this repo's `README.md` à la [A-Frame's](https://github.com/aframevr/aframe#contributing).

**Comment by ngokevin** [comment]
wontfix, defer to a-frame's
