### ISSUE TITLE
Watch documentation branches and automatically deploy updated documentation

### ISSUE THREAD

**Issue by ngokevin** [aframevr/aframe-site#331]
We cherry-pick documentation fixes to the `docs-v0.3.0` branch.

It would be nice if every time that branch was updated, the site automatically reinstalled the multidep docs branch and deployed.

**Comment by cvan** [comment]
how exactly were you thinking about implementing this?

**Comment by ngokevin** [comment]
GitHub webhook to watch the master and documentation branches. Then runs `npm run bumpdocs && npm run deploy`. We could make the bumpdocs script handle all versions.

**Comment by cvan** [comment]
Gotcha. That'd be good so we don't have to hardcode the `0.3.0` version in the `package.json`.

**Comment by ngokevin** [comment]
done
