### ISSUE TITLE
404 on A-frame.io

### ISSUE THREAD

**Issue by Coder206** [aframevr/aframe-site#332]
When navigating to http://A-frame.io, I receive a 404 error message

**Comment by cvan** [comment]
We actually have this domain registered. It should be redirecting. Thanks!

**Comment by Coder206** [comment]
@cvan Can we close the issue?

**Comment by cvan** [comment]
yep, thanks

![image](https://cloud.githubusercontent.com/assets/203725/17992669/59e5e0de-6afe-11e6-97e0-34f08929dbfa.png)
