### ISSUE TITLE
Consider `examples` directory/repo (instead of relying on aframevr/aframe for GitHub Pages Examples)

### ISSUE THREAD

**Issue by cvan** [aframevr/aframe-site#342]
It would be nice to create a separate repo for the `examples`. We could then update the GitHub Pages for the `aframevr/aframe` repo without breaking the A-Frame site which relies on those examples being functional.

The A-Frame Examples shown on https://aframe.io/, with the `<iframe>`s, use https://aframe.io/aframe/examples/. So the URL would change to be https://aframe.io/examples/ 👍

**Comment by ngokevin** [comment]
done for some examples + linking to other examples externally, but will not move all examples to a separate repo or this one.
