### ISSUE TITLE
Link to events, meetups, groups, etc.

### ISSUE THREAD

**Issue by cvan** [aframevr/aframe-site#343]
Such as https://www.meetup.com/Web-VR/, https://w3c.github.io/vr-workshop/, etc.

**Comment by cvan** [comment]
Perhaps we should also create a sub-Reddit (https://www.reddit.com/r/aframevr) and a Meetup.com group (https://www.meetup.com/aframevr/).

**Comment by ngokevin** [comment]
Could design a more pretty Community page to list these

**Comment by cvan** [comment]
I've got a few ideas.

https://zeit.co/
![image](https://cloud.githubusercontent.com/assets/203725/18494583/d30540dc-79cb-11e6-9798-4f2052e276ce.png)

https://www.polymer-project.org/
![image](https://cloud.githubusercontent.com/assets/203725/18494590/dff9f4d6-79cb-11e6-835e-960227965ca5.png)

**Comment by ngokevin** [comment]
wontfix, people can add their groups to /community, or feature on AWOA
