### ISSUE TITLE
Cloudflare CAPTCHA can block access to A-Frame/Mozilla VR sites 

### ISSUE THREAD

**Issue by ngokevin** [aframevr/aframe-site#349]
I was overseas and ran into a CAPTCHA from Cloudflare. Then it failed to load the CAPTCHA so I couldn't access the A-Frame site. On Reddit, we've had reports of this with the mozvr blog as well.

**Comment by cvan** [comment]
I've never seen a CloudFlare CAPTCHA. Scary! I assume it's for DDOS protection. Also being overseas, I learned that Reddit is banned in several countries.

I assume it was this gross thing:

![image](https://cloud.githubusercontent.com/assets/203725/18489954/be436244-79b4-11e6-9c21-ae527e6817ba.png)

**Comment by cvan** [comment]
![image](https://cloud.githubusercontent.com/assets/203725/18489992/f1a381dc-79b4-11e6-884c-b962b8795033.png)

Our Firewall settings were set at Medium. I dropped them to Low:

![image](https://cloud.githubusercontent.com/assets/203725/18490041/24f6f212-79b5-11e6-97b3-8bd9e7c3bbf5.png)

And increased the CAPTCHA "Challenge Passage" time from a 30-minute to 1-hour timeout:

![image](https://cloud.githubusercontent.com/assets/203725/18490067/3d1c28f8-79b5-11e6-89a7-981be965b46a.png)

Do reopen if you see/hear this again from humans.

**Comment by cvan** [comment]
FYI, also made same changes to mozvr.com.

**Comment by ngokevin** [comment]
It's funny that Reddit was not banned in China.
