### ISSUE TITLE
Fix size of `<code>` in headings

### ISSUE THREAD

**Issue by cvan** [aframevr/aframe-site#353]
I think I fixed this in one of the open PRs. Will have to double check. But, I know it's because the `<code>`s are set in `rem`s, but the headings are not.

<a href="https://aframe.io/docs/0.3.0/introduction/faq.html#how-is-a-frame-different-from-vrml">
`https://aframe.io/docs/0.3.0/introduction/faq.html#how-is-a-frame-different-from-vrml` <br>
<img width="746" alt="screen shot 2016-09-20 at 8 09 39 pm" src="https://cloud.githubusercontent.com/assets/203725/18696471/48ea8d82-7f6e-11e6-8caa-f0184ace7c30.png"></a>

**Comment by ngokevin** [comment]
bigger now
