### ISSUE TITLE
Add tips for running a local server

### ISSUE THREAD

**Issue by cvan** [aframevr/aframe-site#355]
Ideally, folks use one of [the A-Frame Boilerplate](https://aframe.io/docs/0.3.0/introduction/getting-started.html#grab-the-boilerplate). But, there are other options, which we should briefly document/link to. It seems not every/many folks are using the Boilerplate w/ Node+npm are instead referencing the `aframe.min.js` URL from our site or downloading it and including it in their own projects.

Possible inspiration to draw from/links to include:

* https://github.com/mrdoob/three.js/wiki/How-to-run-things-locally
* https://chrome.google.com/webstore/detail/web-server-for-chrome/ofhbbkphhbklhfoeikjpcbhemlocgigb (referenced by someone in A-Frame Slack)
* https://www.browsersync.io/

**Comment by cvan** [comment]
(Perhaps this belongs in the FAQ and/or the docs. If FAQ, I can move this issue to the `aframevr/aframe` repo.)

**Comment by ngokevin** [comment]
On Windows, my brother used Mongoose (.exe) with success.

**Comment by cvan** [comment]
nice, cool. @321C4 has used Prepros https://prepros.io/ in the past

**Comment by ngokevin** [comment]
Added to Getting Started page links to mongoose. If you see something else it can be added, send a PR
