### ISSUE TITLE
Link to 'A-Frame Community Slack Channel' is wrong on community page

### ISSUE THREAD

**Issue by gurumukhi** [aframevr/aframe-site#358]
A-Frame Community Slack Channel - Sign up to share your work and join the discussion.

Link to "A-Frame Community Slack Channel" should be http://aframevr.slack.com/

**Comment by cvan** [comment]
thanks for filing. and, yes, this is an issue I forgot to file for. also same issue for the WebVR Slack link. we link to https://aframevr-slack.herokuapp.com so it's easier for people to sign up. but that page doesn't redirect you to https://aframevr.slack.com/ if you're already registered. I have filed an issue to address that: https://github.com/aframevr/aframevr-slack-invite-automation/issues/1

**Comment by ngokevin** [comment]
fixed
