### ISSUE TITLE
Docs `guides/index.md` link isn't getting transformed to `guides/index.html`

### ISSUE THREAD

**Issue by cvan** [aframevr/aframe-site#360]
https://aframe.io/docs/0.3.0/introduction/faq.html

<img width="926" alt="screen shot 2016-09-29 at 8 43 03 pm" src="https://cloud.githubusercontent.com/assets/203725/18980078/665a6a5e-8685-11e6-99b0-8e718781fc4c.png">

**Comment by ngokevin** [comment]
works now
