### ISSUE TITLE
"home feature links" do not look like links

### ISSUE THREAD

**Issue by cvan** [aframevr/aframe-site#378]
These three links look like a tagline at first glance (with text wrapping). And they're uppercase so they actually look like headings too. Since there's no heading nor text-decoration/border, it's unclear that these are in fact links to tools.

![screen shot 2016-10-24 at 5 05 31 pm](https://cloud.githubusercontent.com/assets/203725/19668434/b3036be0-9a0c-11e6-9184-98f58afd7c5e.png)

Perhaps list these links under a `Tools` section à la the `Examples` section. Here's a quick Dev Tools mock:

![screen shot 2016-10-24 at 5 09 23 pm](https://cloud.githubusercontent.com/assets/203725/19668433/b301b5ca-9a0c-11e6-8c8d-0994aca6e3a2.png)

**Comment by ngokevin** [comment]
what if we add text-decoration?

**Comment by ngokevin** [comment]
Or separation from the wordmark:

<img width="249" alt="screen shot 2016-10-24 at 5 23 53 pm" src="https://cloud.githubusercontent.com/assets/674727/19668737/b067fd22-9a0e-11e6-8b1a-7eb9c4091a62.png">

**Comment by cvan** [comment]
What do you think of the treatment in the DevTools mock I posted above? And, yes, I'd agree to adding a `border-bottom` or `text-decoration: underline` to more clearly indicate it's a link.

**Comment by ngokevin** [comment]
I think it de-emphasizes them a bit and tries to pigeonhole them into "Tools" rather than a general top-tier Showcase. And it melds with the example links to create an overwhelming list of links.

Cool, we can add the border

**Comment by cvan** [comment]
Definitely shouldn't be uppercase and that large of font-size. Looks like a tagline wrapped.

**Comment by ngokevin** [comment]
ahyeah i can see that now.
