### ISSUE TITLE
HTML snippet not correctly escaped in Docs > Getting Started > Include the JS Build

### ISSUE THREAD

**Issue by cvan** [aframevr/aframe-site#383]
The [`Getting Started` docs page](https://aframe.io/docs/0.3.0/introduction/getting-started.html) no longer renders correctly the HTML snippet in the [`Include the JS Build` section](https://aframe.io/docs/0.3.0/introduction/getting-started.html#include-the-js-build):

![screen shot 2016-10-25 at 3 31 45 am](https://cloud.githubusercontent.com/assets/203725/19682736/d386cf90-9a63-11e6-8975-15e15337308e.png)

The docs' Markdown page looks okay:

https://github.com/aframevr/aframe/blob/master/docs/introduction/getting-started.md#include-the-js-build

**Comment by ngokevin** [comment]
bumped the docs
