### ISSUE TITLE
spruce up community page

### ISSUE THREAD

**Issue by ngokevin** [aframevr/aframe-site#392]
https://community.algolia.com/
- More images
- Showcase people and geography
- Link to contributing, ecosystem stuff

**Comment by cvan** [comment]
I like the Algolia a bit more, though I think it's just a tad overwhelming at first. For some different inspiration to draw from, and it's arguably quite text heavy but verbose and easily in-page searchable:

https://www.rust-lang.org/en-US/community.html

**Comment by cvan** [comment]
A few more:

* https://teamweek.com/about.html
* https://www.consul.io/community.html
* https://www.packer.io/community/
* https://www.terraform.io/community.html

**Comment by ngokevin** [comment]
went the rust route https://aframe.io/community/
