### ISSUE TITLE
CSP errors with ShopifyVR example

### ISSUE THREAD

**Issue by cvan** [aframevr/aframe-site#402]
```
[Report Only] Refused to display 'https://shopifyvr.myshopify.com/pages/virtual-reality' in a frame because an ancestor violates the following Content Security Policy directive: "frame-ancestors shopifyvr.myshopify.com".
```

<img width="1326" alt="screen shot 2016-11-09 at 10 22 51 pm" src="https://cloud.githubusercontent.com/assets/203725/20166686/4a7bfaf8-a6cb-11e6-8a0a-78acba23b03f.png">
<img src="https://cloud.githubusercontent.com/assets/203725/20166685/4a75176a-a6cb-11e6-8a01-cd11f672ba0c.png">

(Related issue: #384)

**Comment by ngokevin** [comment]
no longer used
