### ISSUE TITLE
Set canonical URL or no-index on older docs

### ISSUE THREAD

**Issue by donmccurdy** [aframevr/aframe-site#408]
Pretty common to do a Google search and see docs from v0.2.0 as the top results. This can be fixed by:

1. Set canonical URL on all pages to the 'master' version. This preserves any SEO benefit of links, but may be more trouble to maintain as page URLs change over time.
2. Disallow `/docs/0.2.0/` in robots.txt or include `<meta name="robots" content="NOINDEX">`.

**Comment by cvan** [comment]
Similar to this for #1:

```html
<link rel="canonical" href="https://aframe.io/docs/0.2.0/<url>">
```

**Comment by ngokevin** [comment]
simple route, went with 2. to not index
