### ISSUE TITLE
Make initial example in introduction work out of the box

### ISSUE THREAD

**Issue by i3games** [aframevr/aframe-site#416]
The first example code on [https://aframe.io/docs/0.4.0/introduction/](https://aframe.io/docs/0.4.0/introduction/) doesn't work because it depends on a texture file being present and gives a rather nasty warning message in the browser.

Given that's the very first code snippet beginners might try copy/paste, it would be nice if this would "just work" like scene content in the example scene, without any dependencies besides A-Frame itself which is CDN'ed here (but not in the examples).

**Comment by cvan** [comment]
Agreed! Thanks for the good suggestion 👍

**Comment by ngokevin** [comment]
fixed
