### ISSUE TITLE
Add Mozilla logo to sidebar on Docs/secondary pages

### ISSUE THREAD

**Issue by cvan** [aframevr/aframe-site#420]
@dmarcos replaced the old `MozVR` wordmark with the new Mozilla wordmark (`Supported by Mozilla`) to the homepage in PR #418. We ought to add the same logo to the sidebar on the other pages (e.g., Docs, Blog, FAQ, etc.).

**Comment by marti1125** [comment]
@cvan I would like to contribute :smile:

**Comment by cvan** [comment]
@marti1125 great! I'd look at

1. set up a local copy of this project: https://github.com/aframevr/aframe-site/blob/master/README.md#local-development
2. refer to this similar Pull Request as inspiration: https://github.com/aframevr/aframe-site/pull/418/files

let me know if you encounter any issues. thanks for helping!

**Comment by marti1125** [comment]
hi @cvan I can run the project =D so Where I have to add the new logo?
Could you specify me please?
https://aframe.io/docs/0.5.0/introduction/

**Comment by cvan** [comment]
@marti1125 

Here are some specific instructions:

1. Copy the HTML for the `Supported by Mozilla` section from [`index.ejs`](https://github.com/dmarcos/aframe-site/blob/fb7370/themes/aframe/layout/index.ejs#L38-L45) to [`sidebar_header.ejs`](https://github.com/aframevr/aframe-site/blob/0f9a4a25/themes/aframe/layout/partials/secondary/sidebar_header.ejs#L75). (Ideally, if you can, instead of just copying it twice, move the HTML into a single, separate `.ejs` file which can be included in both places as an [EJS](http://www.embeddedjs.com/) `partial` [like this one](https://github.com/aframevr/aframe-site/blob/0f9a4a25/themes/aframe/layout/page.ejs#L6).)
2. Move the styles (for `.sponsor`, `.mozilla-logo`, etc.) from [`index.styl`](https://github.com/aframevr/aframe-site/blob/182265d/themes/aframe/source/css/index.styl#L171-L200) to [`_common.styl`](https://github.com/aframevr/aframe-site/blob/182265d/themes/aframe/source/css/_common.styl#L209) (which both `index.styl` and `secondary.styl` require)
3. If you need specific styles for the Mozilla logo on the homepage vs. the Mozilla logo styles for the Docs/secondary pages, then you can put those CSS style overrides [here in the `secondary.styl` file](https://github.com/aframevr/aframe-site/blob/0f9a4a25/themes/aframe/source/css/secondary.styl#L90).

Let me know where you are next and if you need additional help. Thanks for helping!

**Comment by marti1125** [comment]
I added background-color:  #ef2d5e; to .sponsor
but it needs more with and height
at top or at bottom =?
<img width="278" alt="captura de pantalla 2017-04-05 a las 07 50 54" src="https://cloud.githubusercontent.com/assets/223240/24706249/a6d82804-19d4-11e7-852e-2b5ee950e7f1.png">
<img width="277" alt="captura de pantalla 2017-04-05 a las 07 51 01" src="https://cloud.githubusercontent.com/assets/223240/24706250/a6fe2e64-19d4-11e7-8a1b-6060514af647.png">

**Comment by cvan** [comment]
@marti1125 can you show your code on a branch of your fork of the site?

**Comment by cvan** [comment]
this has been done by @marti1125 in PR #424 (thanks!) - and @ngokevin nicely moved the logo on the secondary pages from the sidebar to the footer of the main content area (thanks!)
