### ISSUE TITLE
Enter VR icon disappears on Oculus Internet browser

### ISSUE THREAD

**Issue by adammarcwilliams** [aframevr/aframe-site#426]
When viewing the A-Frame examples on Oculus Internet browser the Enter VR glasses disappear once the page has loaded.

[Video example](https://drive.google.com/file/d/0B6yUlErd0iBTc3Z3NVpGaXJJbDF1RDZfU2Y3Y2ZVemNXZXBB/view?usp=sharing)

Tested with Samsung Galaxy S7 Edge

**Comment by ngokevin** [comment]
This is an aframe issue, not site, but it's been fixed anyways in 060.
