### ISSUE TITLE
On desktop, for blog/documentation, display table of contents as a fixed floating panel on the right side

### ISSUE THREAD

**Issue by ngokevin** [aframevr/aframe-site#429]
1. In Hexo template, create a Table of Contents div. You can see how we're displaying the existing inline table of contents, looping over all the headers, and generating links. Do something similar. The links should point to the heading anchors
2. Style the Table of Contents. Ideally, it won't float/fix until the top of the window scrolls down upon it. After, it should be fixed/floating and visible at all times

<img width="1009" alt="screen shot 2017-05-02 at 4 41 55 pm" src="https://cloud.githubusercontent.com/assets/674727/25643780/56371b16-2f56-11e7-83dd-627e7788f8db.png">

Would also be nice to:

1. Add Suggest Edit button at the top right of the docs page
2. Move search to sidebar

**Comment by cvan** [comment]
Are you trying out ReadMe.io? If so, can you send me a link of what you've got? Thanks 👍

**Comment by ngokevin** [comment]
It's https://whsjs.readme.io/docs

**Comment by cvan** [comment]
gotcha, should've noticed that from the screenshot - thanks

**Comment by ngokevin** [comment]
done
