### ISSUE TITLE
Search doesn't work on 404 pages

### ISSUE THREAD

**Issue by cvan** [aframevr/aframe-site#431]
1. Load https://aframe.io/asd
2. Notice the Console error
3. Type something into the search box
4. Notice the site search doesn't get invoked

<img width="1261" alt="screen shot 2017-05-12 at 2 22 12 am" src="https://cloud.githubusercontent.com/assets/203725/25991926/dbfc0abc-36b9-11e7-86fd-798f153362a8.png">

**Comment by ngokevin** [comment]
https://github.com/aframevr/aframe-site/commit/184676f7256b4ed50bb0dc6ad3d3019c1ce16e13
