### ISSUE TITLE
upgrade license to `CC-BY-SA-4.0`

### ISSUE THREAD

**Issue by cvan** [aframevr/aframe-site#444]
https://creativecommons.org/licenses/by-sa/4.0/

**Comment by divyam3897** [comment]
Hi,
I already see a commit regarding this issue which is fixes it so you can close it or it has something to be done?

**Comment by ngokevin** [comment]
I'd only note this for site images/media, not content/words

**Comment by ngokevin** [comment]
A-Frame is MIT, and can't guarantee everything is CC. let's just leave it at MIT
