### ISSUE TITLE
Bug a-register-element.js:69 - DEPRECATED!!!

### ISSUE THREAD

**Issue by sebekpro** [aframevr/aframe-site#484]
Very big problem, animation not run in chrome!!! Error message: a-register-element.js:69 [Deprecation] document.registerElement is deprecated and will be removed in M73, around March 2019. Please use window.customElements.define instead. See https://www.chromestatus.com/features/4642138092470272 for more details.

**Comment by vincentfretin** [comment]
aframe now uses customElements v1 instead of the old polyfill, so this can be closed @dmarcos

**Comment by dmarcos** [comment]
Yep. This is fixed since 1.4.0
