### ISSUE TITLE
404 - Simple Broken Link in Introduction Docs

### ISSUE THREAD

**Issue by jbvrtx** [aframevr/aframe-site#524]
In the introduction to 1.3.0, there is a broken link that originally lead to supported devices.

Introduction page:
https://aframe.io/docs/1.3.0/introduction/faq.html#which-headsets-browsers-devices-and-platforms-does-a-frame-support
Broken link:
https://aframe.io/docs/1.3.0/introduction/vr-headsets-and-webvr-browsers.html

**Comment by lainshiHenry** [comment]
This link as been fixed in v.1.4.0

Introduction page:
https://aframe.io/docs/1.4.0/introduction/faq.html#which-headsets-browsers-devices-and-platforms-does-a-frame-support

Commit that fixed this issue
https://github.com/aframevr/aframe/pull/5090

**Comment by dmarcos** [comment]
Thank you!
