### ISSUE TITLE
Search on the aframe.io docs not working

### ISSUE THREAD

**Issue by Dirk-27** [aframevr/aframe-site#527]
We can't search with the search field in the top left corner of the page.

https://aframe.io/docs/1.4.0/introduction/

![image](https://user-images.githubusercontent.com/45331389/216095994-abc9feda-6db0-4159-9490-ba091382a48a.png)

**Comment by vincentfretin** [comment]
01/13/2023
https://discord.com/channels/479784974917042186/479787777949433900/1063583512600518686
dmarcos: Gotta still fix doc search for 1.4.0. I saw something changed on the Algolia side on Nov 2022 and no longer indexing new pages. Not sure yet what we have to do but looking into it.

02/15/2023
https://discord.com/channels/479784974917042186/479787777949433900/1075195485205303416
dmarcos: we have to move to the new crawler / API and hadn't had the time. As a workaround you can search in old version 1.3.0 https://aframe.io/docs/1.3.0/introduction/ and just change the link you get to 1.4.0

**Comment by Chabloz** [comment]
In wait for a fix you can search on the master by select it on the version menu:

![image](https://user-images.githubusercontent.com/43348620/236194687-a3601093-b49a-4825-9f05-f985b0257e1d.png)

**Comment by dzg** [comment]
> In wait for a fix you can search on the master

OMG, lifesaver! Thank you!

**Comment by vincentfretin** [comment]
Fixed by https://github.com/aframevr/aframe-site/commit/48ab5f4be57454095e81b07509a82019f72c9ec1
The issue can be closed @dmarcos

**Comment by dmarcos** [comment]
thanks
