### ISSUE TITLE
Getting an Unhandled Rejection TypeError when trying to run AFrame website locally

### ISSUE THREAD

**Issue by lainshiHenry** [aframevr/aframe-site#529]
Repo: aframe-site

I have forked the aframe-site repo and trying to run the code locally. However, after **npm install** and then **npm start**, i'm faced with the error message for the index.ejs file.

Any help is appreciated :)

Screenshot of full error below:
<img width="955" alt="image" src="https://github.com/aframevr/aframe-site/assets/27880002/e66b9988-f028-4285-844e-9f572b031a26">

**Comment by vincentfretin** [comment]
You can close this one @dmarcos

**Comment by dmarcos** [comment]
thanks
