### ISSUE TITLE
All internal links broken

### ISSUE THREAD

**Issue by vincentfretin** [aframevr/aframe-site#541]
For example https://aframe.io/docs/1.6.0/introduction/
click on Installation link, it goes to https://aframe.io/docs/1.6.0/introduction/installation.md instead of https://aframe.io/docs/1.6.0/introduction/installation.html
so not transforming .md to .html
regression from #539 changes?

**Comment by vincentfretin** [comment]
fixed in #542

**Comment by dmarcos** [comment]
Thanks!
