### ISSUE TITLE
Improve responsive layout of docs on mobile/desktop

### ISSUE THREAD

**Issue by cvan** [aframevr/aframe-site#77]

**Comment by cvan** [comment]
The footer nav leaves a lot to be desired. Turning that "Menu" into a slide-out nav is probably what needs to be done.

**Comment by ngokevin** [comment]
Slide out nav
![nav](https://cloud.githubusercontent.com/assets/674727/19783738/ea947328-9c47-11e6-8e63-d06308b8ccbb.gif)
