### ISSUE TITLE
Fix position of labels for code snippets when horizontally scrolling

### ISSUE THREAD

**Issue by cvan** [aframevr/aframe-site#84]
https://aframe.io/docs/primitives/

<img src="https://cloud.githubusercontent.com/assets/203725/11862628/159691d6-a442-11e5-8a01-6e1891facdf3.png" width="70%">

**Comment by cvan** [comment]
https://aframe.io/docs/primitives/

**Comment by amitsin6h** [comment]
want to work assign me @cvan

**Comment by ngokevin** [comment]
wontfix
