### ISSUE TITLE
Fix incorrect Markdown smartypants curly quotation marks for 's

### ISSUE THREAD

**Issue by cvan** [aframevr/aframe-site#90]
https://aframe.io/docs/guide/installation.html

<img src="https://cloud.githubusercontent.com/assets/203725/11864186/4981efd8-a44f-11e5-90b0-6dbb3146028b.png" width="25%">

**Comment by amitsin6h** [comment]
want to work assign me @cvan

**Comment by ngokevin** [comment]
wontfix
