### ISSUE TITLE
Have link checker check relative links too

### ISSUE THREAD

**Issue by cvan** [aframevr/aframe-site#91]
I've been adding to the [Docs](https://aframe.io/docs/) a lot of internal links cross-referencing pages.

Let's beef up the [link checker](https://github.com/aframevr/aframe-site-dev/blob/master/scripts/checkLinks.js) to check for internal links too.

**Comment by cvan** [comment]
We'll probably need to run it on the `public/` output (what's generated by `npm run generate`).

**Comment by ngokevin** [comment]
i did on aframe repo side
