### ISSUE TITLE
Figure out how to fix images of Twitter + FB Cards for CodePen links

### ISSUE THREAD

**Issue by cvan** [aframevr/aframe-site#95]
[CodePen is awesome and actually generates screenshots for use with Twitter + FB Cards ](http://blog.codepen.io/2013/07/16/pens-have-twitter-cards/).

Unfortunately, the [Twitter image](http://s3-us-west-2.amazonaws.com/i.cdpn.io/358505.BjygdO.80a8d6b3-2f2a-45a6-ac1c-136368bfad77.png) and the [Facebook image](http://codepen.io/team/mozvr/pen/BjygdO/image/large.png) both blank.

My theory is our `loaded` events take too long and the screenshot doesn't wait. But I could be wrong.

<hr>

Not sure if this is a [core issue](https://github.com/aframevr/aframe-core/issues). It likely is, but could be an [aframe (template) issue](https://github.com/aframevr/aframe/issues). When we figure out what the cause is, we can move the issue accordingly.

**Comment by cvan** [comment]
For reference see https://twitter.com/whoyee/status/677296026600902656

<img src="https://cloud.githubusercontent.com/assets/203725/11865810/6a919492-a45b-11e5-9c34-1db8894e4a04.png" width="50%">

**Comment by ngokevin** [comment]
Glitch > CodePen now
